[book]
authors = ["Ky Anh"]
language = "en"
multilingual = true
src = "src"
title = "ğŸ’ğŸŒ¿ğŸ’"

[output.html]
additional-css = ["./theme/catppuccin.css"]
default-theme = "latte"
preferred-dark-theme = "mocha"
